# 데이터 삭제하기

```MySQL
DELETE FROM 테이블이름
WHERE 조건식;
```

# 데이터 수정하기

```MySQL
UPDATE 테이블이름
SET 컬럼이름=새값
WHERE 조건식;
```

# 제약조건

- 데이터를 입력할 때 실행되는 데이터 입력 규칙
- 테이블을 만들거나 변경하면서 설정함

제약조건|의미
-|-
NOT NULL|이 컬럼에는 NULL값을 저장할 수 없음
UNIQUE|이 컬럼의 값들은 서로 다른 값을 가져야 함
DEFAULT|이 컬럼에 입력값이 없을 시 기본값이 설정됨
PRIMARY KEY|이 컬럼은 테이블의 기본키. NOT NULL과 UNIQUE특징을 모두 가짐
FOREIGN KEY|이 컬럼은 테이블의 외래키. 이 컬럼은 다른 테이블의 특정 컬럼을 참조함

```MySQL
CREATE TABLE 테이블이름 (
             컬럼이름 데이터타입 제약조건,
             컬럼이름 데이터타입 제약조건,
             ...);
```

```MySQL
CREATE TABLE new_mypokemon (
             number INT PRIMARY KEY,
             name VARCHAR(20) UNIQUE,
             type VARCHAR(10) NOT NULL,
             attack INT DEFAULT 0,
             defense INT DEFAULT 100,
             FOREIGH KEY(number) REFERENCES mypokemon(number));      # FOREIGN KEY는 참조하는 테이블의 PRIMARY KEY여야 함
```

# 사용자 확인하기

### MySQL 기본 데이터베이스인 mysql 데이터베이스 선택하기

```MySQL
USE mysql;
```

### 사용자 목록 조회하기

```MySQL
SELECT user, host FROM user;
```

# 사용자 생성, 삭제하기

### 사용자 생성하기

```MySQL
CREATE USER 사용자이름@ip주소;
```

### 비밀번호와 함께 사용자 생성하기

```MySQL
CREATE USER 사용자이름@ip주소 IDENTIFIED BY '사용자비밀번호';     # 문자열이기 때문에 따옴표로 감싸줘야 함
```

### 사용자 삭제하기

```MySQL
DROP USER 사용자이름;
```

# 권한 부여하기

### 권한 부여하기

```MySQL
GRANT 권한 ON 데이터베이스이름.테이블이름 TO 사용자이름@ip주소;
```

### 권한 확인하기

```MySQL
SHOW GRANTS FOR 사용자이름@ip주소;
```

### 권한 삭제하기

```MySQL
REVOKE 권한 ON 데이터베이스이름.테이블이름 FROM 사용자이름@ip주소;
```

### 권한 적용하기

```MySQL
FLUSH PRIVILEGES;
```

# 트랜잭션

### 트랜잭션 시작하기

```MySQL
START TRANSACTION;
```

### 트랜잭션 확정하기

```MySQL
COMMIT;
```

### 트랜잭션 이전으로 돌아가기

```MySQL
ROLLBACK;
```

# 세이브포인트

### 세이브포인트 만들기

```MySQL
SAVEPOINT 세이브포인트이름;
```

### 세이브포인트로 돌아가기

```MySQL
ROLLBACT TO 세이브포인트이름;
```